# Permalinks
permalink:           pretty

# Setup
title:               Writings Of Three Musketeers
tagline:             
url:                 https://writingsofthreemusketeers.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Three Musketeers
  url:               
  email:             writingsofthreemusketeers@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  
  pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
